#!/usr/bin/env python3
"""Generate the app-specific mobile Stroke dictionary from pinned rime-stroke data."""

from __future__ import annotations

import argparse
import pathlib
import re
import unicodedata
import urllib.request
from dataclasses import dataclass
from typing import Iterable


SOURCE_REVISION = "3a4b0f4013e2b4c14b1e80c92b1d4723eb65f39c"
SOURCE_URL = (
    "https://raw.githubusercontent.com/rime/rime-stroke/"
    f"{SOURCE_REVISION}/stroke.dict.yaml"
)
VALID_CODE = re.compile(r"^[hspnz]+$")

# These are valid independently encoded Han characters, but common complete
# characters should win the first page for a one- or two-stroke query.
LOW_PRIORITY_RADICAL_FORMS = frozenset(
    "亻氵扌忄犭礻衤讠饣纟钅阝刂灬爫丬疒罒耂艹辶廴"
)


@dataclass(frozen=True)
class Entry:
    text: str
    code: str
    weight: int | None = None

    def serialize(self) -> str:
        fields = [self.text, self.code]
        if self.weight is not None:
            fields.append(str(self.weight))
        return "\t".join(fields)


def is_complete_han(text: str) -> bool:
    if len(text) != 1:
        return False
    if text == "〇":
        return True
    name = unicodedata.name(text, "")
    return name.startswith("CJK UNIFIED IDEOGRAPH-") or name.startswith(
        "CJK COMPATIBILITY IDEOGRAPH-"
    )


def normalize_han(text: str) -> str | None:
    if not is_complete_han(text):
        return None
    normalized = unicodedata.normalize("NFKC", text)
    return normalized if is_complete_han(normalized) else None


def parse_entries(source: str) -> list[Entry]:
    in_data = False
    seen: set[tuple[str, str]] = set()
    entries: list[Entry] = []
    for raw_line in source.splitlines():
        line = raw_line.strip()
        if not in_data:
            in_data = line == "..."
            continue
        if not line or line.startswith("#"):
            continue
        fields = raw_line.split("\t")
        if len(fields) < 2:
            continue
        text = normalize_han(fields[0].strip())
        code = fields[1].strip()
        if text is None or VALID_CODE.fullmatch(code) is None:
            continue
        key = (text, code)
        if key in seen:
            continue
        seen.add(key)
        entries.append(
            Entry(
                text=text,
                code=code,
                weight=1 if text in LOW_PRIORITY_RADICAL_FORMS else None,
            )
        )
    return entries


def validate(entries: Iterable[Entry]) -> None:
    materialized = list(entries)
    if not materialized:
        raise ValueError("generated Stroke dictionary is empty")
    invalid = [entry for entry in materialized if not is_complete_han(entry.text)]
    if invalid:
        raise ValueError(f"non-Han entries escaped generation: {invalid[:3]}")
    if any(entry.text == "\U00018800" for entry in materialized):
        raise ValueError("Tangut component U+18800 escaped generation")


def render(entries: list[Entry]) -> str:
    header = f"""# Rime dictionary: t9_stroke
# encoding: utf-8
#
# Generated by scripts/generate_t9_stroke_dictionary.py.
# Source: rime/rime-stroke @ {SOURCE_REVISION}
# Do not edit this file manually.

---
name: t9_stroke
version: "{SOURCE_REVISION[:12]}"
sort: by_weight
use_preset_vocabulary: true
max_phrase_length: 1
...

"""
    return header + "\n".join(entry.serialize() for entry in entries) + "\n"


def load_source(path: pathlib.Path | None) -> str:
    if path is not None:
        return path.read_text(encoding="utf-8")
    with urllib.request.urlopen(SOURCE_URL, timeout=30) as response:
        return response.read().decode("utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=pathlib.Path)
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parents[1] / "t9_stroke.dict.yaml",
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    entries = parse_entries(load_source(args.source))
    validate(entries)
    generated = render(entries)
    if args.check:
        current = args.output.read_text(encoding="utf-8")
        if current != generated:
            raise SystemExit(f"{args.output} is stale; regenerate it")
        return
    args.output.write_text(generated, encoding="utf-8")
    print(f"wrote {len(entries)} Han entries to {args.output}")


if __name__ == "__main__":
    main()
